[package]
name="casino"
authors=["Liam Kent"]
version="0.1.0"

[build]
platforms=["whiley", "boogie"]

[build.whiley]
verify=false

[build.boogie]
timeout=30
verify=false

[check]
min=-1
max=1
length=3

